# Generated by Django 6.0.4 on 2026-04-30 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(db_column='chat_id', primary_key=True, serialize=False, verbose_name='채팅 식별 번호')),
                ('chat_title', models.CharField(max_length=50, verbose_name='채팅 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 식별 번호')),
            ],
            options={
                'verbose_name': '채팅목록',
                'verbose_name_plural': '채팅목록',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('message_id', models.AutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '사용자'), ('system', '시스템')], max_length=20, verbose_name='역할')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='채팅 목록')),
            ],
            options={
                'verbose_name': '상세 채팅',
                'verbose_name_plural': '상세 채팅',
                'db_table': 'chat_log',
            },
        ),
    ]
